### ISSUE TITLE
Replace "sudo" usage with "become"

### ISSUE THREAD

**Issue by nbibler** [weareinteractive/ansible-newrelic#11]
The direction of current and future Ansible (as of 1.9+) appears to be [removing `sudo` and using `become`](http://docs.ansible.com/ansible/become.html) for privilege escalation.

To that end, usage of `sudo` should be replaced with `become` and tasks which require escalated privileges should likely individually define the `become` usage.

**Comment by franklinkim** [comment]
thx to @smiller171 see #12
