### ISSUE TITLE
1.4.1/1.4.2 releases not on Galaxy

### ISSUE THREAD

**Issue by geerlingguy** [weareinteractive/ansible-newrelic#14]
It seems notifications from Travis to Galaxy have been flaky lately. It looks like the 1.4.1 and 1.4.2 releases never made it to Ansible Galaxy: https://galaxy.ansible.com/franklinkim/newrelic/

Note also—the link from this repository's README badge is going to your `apt` project on Galaxy instead of `newrelic` (link should be the one above), and it's the old style URL.

**Comment by franklinkim** [comment]
That's annoying... will go back to hitting that button than, just to make sure
