### ISSUE TITLE
Role is at new namespace (weareinteractive) on Galaxy

### ISSUE THREAD

**Issue by geerlingguy** [weareinteractive/ansible-newrelic#22]
The install instructions for Galaxy are incorrect in the README, as this role is now available at https://galaxy.ansible.com/weareinteractive/newrelic — so it should be like `ansible-galaxy install weareinteractive.newrelic`.

**Comment by geerlingguy** [comment]
Well... if I run that I get:

```
- downloading role 'newrelic', owned by weareinteractive
[WARNING]: - weareinteractive.newrelic was NOT installed successfully: - sorry, weareinteractive.newrelic was not found
on https://galaxy.ansible.com/api/.
```

So the instructions in the README are still correct, but Galaxy is not showing that role as being available under the `franklinkim` namespace, and is showing the command in the original comment here.

Seems confusing either way :/

**Comment by franklinkim** [comment]
Hi, haven't had the time to update all my roles yet and doing it more or less on request...
The new release (v1.8.0) should do the trick.

**Comment by geerlingguy** [comment]
@franklinkim - Great, thanks! I can confirm it is working in the new namespace now:

```
$ ansible-galaxy install --force weareinteractive.newrelic
- downloading role 'newrelic', owned by weareinteractive
- downloading role from https://github.com/weareinteractive/ansible-newrelic/archive/1.8.0.tar.gz
- extracting weareinteractive.newrelic to /Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/provisioning/roles/weareinteractive.newrelic
- weareinteractive.newrelic (1.8.0) was installed successfully
```
