### ISSUE TITLE
This doesn't seem to enable the docker container monitoring

### ISSUE THREAD

**Issue by anentropic** [weareinteractive/ansible-newrelic#5]
It says the default is `newrelic_disable_docker: no` ...but I don't think this actually does the step to enable Docker monitoring in the first place:
https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/enabling-new-relic-servers-docker

I'm not getting any Docker monitoring after using this role

**Comment by franklinkim** [comment]
Hi, actually haven't used newrelic's docker monitoring myself yet... you probably need to do more than just using this role as it only installs the daemon.

This role has a template for `nrsysmond.cfg` and I added some variables to be configured as a starting point (can definitely be extended, help welcome) which includes the option:

```
#
# Option : disable_docker
# Type   : boolean
# Value  : Set to true to disable Docker container statistics gathering.
# Default: false
#
disable_docker={{ newrelic_disable_docker | to_nice_json }}
```

so till now that's only what it does in account to docker monitoring.

If you figure out what needs to be done we can add it to this role or make a `ansible-newrelic-docker`...
